apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/image.dockerRepositoryCheck: 2018-08-04T02:09:47Z
  generation: 1
  name: alpine
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: alpine:latest
    generation: 1
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source