apiVersion: v1
kind: Service
metadata:
  labels:
    app: galaxy
    service: web
  name: web2
spec:
  ports:
  - name: port-8000-tcp
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: galaxay
    service: web2
  sessionAffinity: None
  type: ClusterIP